name: Feature Request
description: File a feature request. 
title: '[FEATURE]: <Software> - <Summary>'
labels: ['FEATURE','TRIAGE']
body:

  - type: markdown
    attributes:
      value: |
        <br>Before creating the request, see the existing issues to check if
        your case has not been addressed already. If it has, you may also find information about workarounds, resolution, and progress.

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the problem or proposed feature. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution Description
      description: If you have a solution in mind, describe it.

  - type: textarea
    attributes:
      label: Alternative Description
      description: Have you considered any alternative solutions or workarounds?